const Data = [
  {
    id: 1,
    name: "Taylor Swift - The Eras Tour",
    location: "New York, Mỹ",
    date: "15/11/2024",
    cost: 150,
  },
  {
    id: 2,
    name: "Coldplay - Music of the Spheres World Tour",
    location: "London, Anh",
    date: "20/12/2024",
    cost: 180,
  },
  {
    id: 3,
    name: "BTS - Map of the Soul Tour",
    location: "Seoul, Hàn Quốc",
    date: "10/01/2025",
    cost: 250000,
  },
  {
    id: 4,
    name: "Ed Sheeran - + - = ÷ x Tour",
    location: "Paris, Pháp",
    date: "18/10/2024",
    cost: 120,
  },
  {
    id: 5,
    name: "BLACKPINK - Born Pink World Tour",
    location: "Tokyo, Nhật Bản",
    date: "05/12/2024",
    cost: 20000,
  },
  {
    id: 6,
    name: "Ariana Grande - Sweetener World Tour",
    location: "Los Angeles, Mỹ",
    date: "02/11/2024",
    cost: 140,
  },
  {
    id: 7,
    name: "Bruno Mars - 24K Magic World Tour",
    location: "Rio de Janeiro, Brazil",
    date: "25/10/2024",
    cost: 500,
  },
  {
    id: 8,
    name: "The Weeknd - After Hours Tour",
    location: "Toronto, Canada",
    date: "08/11/2024",
    cost: 220,
  },
  {
    id: 9,
    name: "Lady Gaga - Chromatica Ball",
    location: "Berlin, Đức",
    date: "22/10/2024",
    cost: 180,
  },
  {
    id: 10,
    name: "Justin Bieber - Justice World Tour",
    location: "Sydney, Úc",
    date: "12/12/2024",
    cost: 300,
  },
  {
    id: 11,
    name: "Real Madrid vs. Barcelona - El Clásico",
    location: "Madrid, Tây Ban Nha",
    date: "29/10/2024",
    cost: 250,
  },
  {
    id: 12,
    name: "Manchester United vs. Manchester City - Derby Manchester",
    location: "Manchester, Anh",
    date: "05/11/2024",
    cost: 200,
  },
  {
    id: 13,
    name: "PSG vs. Olympique Lyon - Ligue 1",
    location: "Paris, Pháp",
    date: "15/10/2024",
    cost: 180,
  },
  {
    id: 14,
    name: "Juventus vs. Inter Milan - Serie A",
    location: "Turin, Ý",
    date: "12/11/2024",
    cost: 150,
  },
  {
    id: 15,
    name: "Chelsea vs. Arsenal - Premier League",
    location: "London, Anh",
    date: "20/12/2024",
    cost: 180,
  },
  {
    id: 16,
    name: "Los Angeles Lakers vs. Golden State Warriors - NBA",
    location: "Los Angeles, Mỹ",
    date: "28/10/2024",
    cost: 250,
  },
  {
    id: 17,
    name: "Chicago Bulls vs. Miami Heat - NBA",
    location: "Chicago, Mỹ",
    date: "05/11/2024",
    cost: 200,
  },
  {
    id: 18,
    name: "Boston Celtics vs. Brooklyn Nets - NBA",
    location: "Boston, Mỹ",
    date: "18/10/2024",
    cost: 220,
  },
  {
    id: 19,
    name: "Dallas Mavericks vs. Phoenix Suns - NBA",
    location: "Dallas, Mỹ",
    date: "03/12/2024",
    cost: 190,
  },
  {
    id: 20,
    name: "New York Knicks vs. Philadelphia 76ers - NBA",
    location: "New York, Mỹ",
    date: "10/11/2024",
    cost: 230,
  },
];

export { Data };
